50_dummy_resource/README.md

Also added information for the current open issue for fly/the UI regarding the pause feature.

Updated instructions to include in, out, and check files.

---

07_myresource_jobs/run.sh
08_pipeline_jobs/run.sh
09_task_inputs/run.sh
10_deploy_app/run.sh
12_run_tests_before_deploy/run.sh
20_versions_via_s3/run.sh
20_versions_via_s3/stub.example.yml
35_push_docker_image/run.sh
36_pull_docker_image/run.sh
40_github_release_input/run.sh
44_bosh_io/run.sh
45_bosh_deploy/run.sh
46_bosh_manifest_spiff_merge/run.sh
47_spiff_merge_redis_to_bosh_lite/run.sh
50_dummy_resource/run.sh
51_dummy_resource_docker_image/run.sh
60_multi_jobs_bosh_micro_build/run.sh

Thank you for this great tutorial on Concourse!

Fixes all run.sh scripts to get the examples working again with this version of the fly cli

---

04_basic_pipeline/README.md

Thought I would fix it since I saw it.

updated README number

---

35_push_docker_image/README.md

It looked like the README had gotten a bit out of date so I updated it to match the current setup

Update README to reflect the current configuration

---

README.md

Just refresh it to make more up to date

Update kernel/distro version line

---

Vagrantfile

the cable was disconnected on startup..

---

46_bosh_manifest_spiff_merge/pipeline-base-save.yml
46_bosh_manifest_spiff_merge/pipeline-base-show.yml
46_bosh_manifest_spiff_merge/spiff-merge-and-save.sh
47_spiff_merge_redis_to_bosh_lite/README.md
47_spiff_merge_redis_to_bosh_lite/pipeline-bosh-deploy.yml
47_spiff_merge_redis_to_bosh_lite/pipeline-build-task-image.yml
47_spiff_merge_redis_to_bosh_lite/task_docker_image/Dockerfile
47_spiff_merge_redis_to_bosh_lite/task_docker_image/spiff-merge-and-save
51_dummy_resource_docker_image/run.sh

Note branch name for tutorial resource must be as-is until after this is merged to master.

Fixes spiff merges in step $46

---

README.md

Hopefully this is a little clearer.

Reword benefits/downsides section in lesson 05. [Fixes #41]

---

52_dummy_resource/README.md
README.md

Linked all chapters, regarding https://github.com/starkandwayne/concourse-tutorial/issues/84

fixed heading in 52, listed all chapters in main readme

---

11_task_outputs_to_inputs/create_some_files.sh

Reverts starkandwayne/concourse-tutorial#103

Revert "11_task_outputs_to_inputs - avoid folder exist error message"

---

README.md

Add setup instructions targeted for windows users.

Add Windows Instructions

---

docs/miscellaneous/docker-images.md

p.s Great tutorial!  Love the new site for it too

correct path in docker images tutorial

---

docs/basics/basic-pipeline.md
docs/basics/destroy-pipelines.md
docs/basics/task-outputs-to-inputs.md
docs/basics/watch-job-output.md

Thanks for the great tutorial! This just updates a few things I noticed while reading through it. A couple are debatable punctuation changes so feel free to cherry-pick if you'd like.

minor wording changes in tutorial

---

docs/miscellaneous/docker-images.md

`hello-world-docker-image`  repository was invalid

Fix docker-images build pipeline resource

---

README.md
docs/basics/pipeline-resources.md
docs/basics/publishing-outputs.md
docs/basics/task-hello-world.md
docs/index.md
docs/miscellaneous/slack-notifications.md
docs/miscellaneous/yaml-editors.md
docs/realworld-pipelines.md
tutorials/basic/11-task-inputs-bonus/README.md
tutorials/basic/publishing-outputs/bump-timestamp-file.sh

did a quick find and replace to change references from the old domain to the new domain

changing references from concourse.ci -> concourse-ci.org

---

docs/basics/task-hello-world.md

The current steps assume the repo has been cloned, but I could not
find a previous step that included this. Add the clone to make
this pasteable.

Add step to clone the repo

---

docs/basics/parameters.md
docs/basics/secret-parameters.md
tutorials/basic/parameters/test.sh

In staying with the Garfield namespace for this example, correct the spelling of Odie.

The dog's name in Garfield is Odie

---

docs/index.md
docs/miscellaneous/slack-notifications.md
docs/miscellaneous/yaml-editors.md

The old links gave 404 dude to change in address, so putting correct links

Fix Concourse main site links

---

docs/basics/publishing-outputs.md

Added note saying the key should not be generated using a passphrase.

Added note for key selection error

---

docs/basics/secret-parameters.md

Credential Management page https://concourse-ci.org/creds.html mentions 4 of them (https://github.com/concourse/docs/blob/0a149283f50fc933a186830f95bcd309f37d8073/lit/setup-and-operations/operation/creds.lit#L11)

Added credential managers

---

docs/basics/basic-pipeline.md

- The tutorial itself said that this needed updating to reflect the new
Concourse UI, so I've done that and removed the note.
- This is a _large_ GIF, but I recorded the sequence of steps as quickly
as I could, and any more compression made it look awful. Any tips on
how to get the size down further are greatly appreciated!

Update the hello world job pipeline GIF

---

docs/basics/pipeline-resources.md

I did not know which `pipeline.yml` to edit

Add missing path

---

docs/basics/watch-job-output.md

grammar changes

---

docker-compose.yml

v4.2.1 is mighty old and thought I could lend a hand to update.
Signed-off-by: Max Knee <Max_Knee@comcast.com>

Bumping concourse to 5.6.0

---

docs/index.md

Updated the windows issues faced and resolution

Updated the windows issues faced and resolution

---

docker-compose.yml

https://github.com/starkandwayne/concourse-tutorial/issues/236

fix(236): Update concourse artifact

---

docs/basics/task-hello-world.md

I wasn't sure what the default credentials were when I first read this, had to navigate back to the previous page and read the alias command.

Add default credentials note

---

docs/basics/secret-parameters.md

when using VirtualBox ran into error about disk mount timing out, found article about using Docker instead and this worked without problem

using docker instead of VirtualBox
