starkandwayne/concourse-tutorial

12_run_tests_before_deploy/pipeline.yml
12_run_tests_before_deploy/stub.example.yml

Fix tutorial 12

---

08_pipeline_jobs/pipeline.yml

I added trigger: true to both get actions. If you update the gist, the pipeline will work now. 
This will only work if the job is triggered by a gist update. If you manual run the first job the second one will not be executed. 
fix #14

Added trigger: true to autostart both jobs after update.

---

README.md

For users who aren't running Homebrew, /usr/local will be owned by root. Also, /usr/local/bin might not exist.

Update `fly` install steps

---

45_bosh_deploy/pipeline.yml

I didn't work through all your examples, but instead picked 45 specifically, because it's interesting to me. Maybe this bug wasn't uncovered, because the stemcell is already uploaded in one of the previous examples. Anyway, this fixes it.

Fix bosh_deploy pipeline by adding stemcells

---

12_publishing_outputs/bump-timestamp-file.yml

Found a short-term alternative. We'll want to revisit this and create our own. This at least fixes the broken tutorial segment.

The concourse/concourse-ci Docker image went away. 

---

15_deploy_cloudfoundry_app/README.md

Noticed this while reading through the tutorials

Fix typo: Herkou => Heroku

---

46_bosh_manifest_spiff_merge/pipeline-base-save.yml
47_spiff_merge_redis_to_bosh_lite/pipeline-build-task-image.yml

These two manifests had to use branch `fix-46-spiff-merge` until the fixes were actually merged to master. Now that #74 has been merged in it's safe to point these back at `master`.

Update steps 46&47 to use master branch.

---

35_push_docker_image/run.sh
36_pull_docker_image/run.sh
45_bosh_deploy/README.md
45_bosh_deploy/credentials.example.yml
45_bosh_deploy/pipeline.yml
46_bosh_manifest_spiff_merge/run.sh
47_spiff_merge_redis_to_bosh_lite/README.md
47_spiff_merge_redis_to_bosh_lite/credentials.example.yml
47_spiff_merge_redis_to_bosh_lite/pipeline-bosh-deploy.yml
47_spiff_merge_redis_to_bosh_lite/run.sh
51_dummy_resource_docker_image/run.sh
70_pivnet_updates/run.sh
ci/README.md
ci/bin/bosh-login
ci/bin/create-credentials-yml
ci/bin/create-credentials-yml.rb
ci/bin/deploy-concourse
ci/bin/run-all-lessons
ci/ci_image/Dockerfile
ci/ci_image/gemrc
ci/lib/pretty-output.sh
ci/lib/shared-functions.sh
ci/manifest-vsphere-4.yml
ci/manifest.example.yml
ci/manifest.yml
ci/pipeline.yml

CI for the tutorial itself so that, among other things, we don't have to manually test everything each time there is a new release of Concourse.
There's more work to be done:
- `run.sh` for the first back of lessons is still a no-op
- Lots of duplication and inconsistency in run scripts
- Versions of a few tools need updating
- Concourse deployment could be simplified to use fewer VMs

Added CI for the tutorial itself.

---

README.md

Fly version `2.7.0`
When running `04 - Basic pipeline step`
```
fly --target tutorial set-pipeline --config pipeline.yml --pipeline helloworld 
```
the output now shows `dir: ""`  , a new attribute.
```
jobs:
job job-hello-world has been added:
name: job-hello-world
public: true
plan:
- task: hello-world
config:
platform: linux
image_resource:
type: docker-image
source:
repository: busybox
run:
path: echo
args:
- hello world
dir: ""
```

Concourse 2.7.0 Change in Job output of step 04 - Basic pipeline

---

README.md

The instructions tell you to paste in your private key but don't mention that you need to add a pipe symbol

Added a warning in section 12

---

README.md

Simple changes:
* Used relative links as opposed to absolute links (as described in [github guide](https://help.github.com/articles/basic-writing-and-formatting-syntax/#relative-links)) - use the file in your favourite editor, without the need for a browser.
* Added `Go to Top` as way to make the navigation even easier - often times I had to go back check previous examples and it is really easy to go to the top and then click on the section.
These changes helped me while reading through the README file. Hope it makes sense.

Relative links in the README

---

11_task_outputs_to_inputs/create_some_files.sh

- avoid folder exist error message
mkdir: can't create directory 'some-files': File exists

11_task_outputs_to_inputs - avoid folder exist error message

---

45_bosh_deploy/run.sh

Reverts starkandwayne/concourse-tutorial#111
Apparently it's there for backward compatibility: https://github.com/starkandwayne/concourse-tutorial/blob/master/docs/alex-suraci-cfsummit-2015.md#debuggable-builds
cc @Dewtah

Revert "configure syntax in line 33 unnecessary"

---

docs/basics/pipeline-resources.md

Path explanation doesn't contain prefix `tutorials/basic`

Fix path explanation for pipeline resources

---

docs/basics/task-inputs.md

It was not immediately obvious in this section what command
was being run since it is easy to miss seeing the "e". Add a blurb
about this and about short-hand for commands so we avoid losing
the readers.

Add blurb about short-hand commands

---

docs/basics/pipeline-resources.md

This covered a bit more later in the same page but it took me some time to figure out why we were using the path relative to that folder, this small blurb should add some clarification and leaves the more detailed explanation for further down in the doc.

Add clarification about location of the git clone

---

docs/basics/basic-pipeline.md

Without this command the first job never runs:

Basic pipeline: need to unpause the job too

---

docs/basics/pipeline-resources.md

The documentation states that the previous pipeline was called ```helloworld`` and that there will be a delta.  The previous pipeline is actually called ```hello-world```.  The means that the new pipeline will not update the existing one and there will be no delta.
To fix this issue change to ```hello-world```

Incorrect Reference to Previous Pipeline

---

docs/miscellaneous/slack-notifications.md

Other steps in the doc use a hyphen '-' to reference the slack-webhook instead of underscore '_', it looks like hyphen was intended.

Replace underscore with hyphen to align with doc

---

docs/index.md

The basic auth has to be explicit in the cli as -u for user and -p for password.

User and pasword were not prompted [4.2]

---

docs/basics/basic-pipeline.md
docs/basics/parameters.md
docs/basics/pipeline-resources.md
docs/basics/publishing-outputs.md

1. In the Introduction section, we run the command to create our initial Concourse CI environment:
`fly --target tutorial login --concourse-url http://127.0.0.1:8080 -u admin -p admin`
Later, we have a [basic-pipline section](https://concoursetutorial.com/basics/basic-pipeline/#login-to-concourse-web-ui) instructing the user to log in, with a parapgraph following stating authentication is disabled. Considering most users will be following the guide to set the specified username & password, I suggest removing the following paragraph.
> Why did you not have to enter any username/password? Excellent question, indeed. It's because your current fly -t tutorial deployment of Concourse has had authentication disabled. In a future lesson we will upgrade to a more robust installation of Concourse …

Documentation Improvements

---

docs/basics/task-scripts.md

The tutorial previously said "as we did above" which confused me since it was at the top of the tutorial.

Add link to Docker image task with uname

---

docs/miscellaneous/versions-and-buildnumbers.md

https://github.com/Python-Markdown/markdown/issues/3
_I did this directly in GitHub web ui and it doesn't let me exclude the end-of-file normalisation. That's why that last line shows up as a change as well._

Fix nested list item indentation

---

docs/basics/publishing-outputs.md
tutorials/basic/publishing-outputs/bump-timestamp-file.sh

"echo $(date)" does the same thing as "date"

remove useless subshell from date commands

---

mkdocs.yml

The index title currently differs from the title of the page. This PR changes the index title to match the page title.

Match index and header titles

---

docs/basics/task-hello-world.md

Being new to both Concourse and Docker, it took me a bit to figure out I needed to restart Concourse in the local container after killing it at the end of the Introduction tutorial, and then a bit to figure out I had to do it from within the same directory.  Thought I'd try to help out other ignoramuses like myself.

Added instructions to restart the Concourse server

---

docs/index.md

Default credentials are now test/test: https://github.com/concourse/concourse-docker

Default credentials updated.

---

docs/basics/secret-parameters.md

Add a link to additional-dependencies for Ubuntu, macOS or CentOS in the secret-parameters tutorial in order for installation to progress.

link to additional-dependencies

---

docs/basics/pipeline-resources.md

The "Concourse Tutorial**s** Miscellaneous section..." phrase suggests that either an apostrophe need to be added in "Tutorial**s**" to produce "Tutorial'**s**" or one should rephrase to eliminates the "s" at the end.

[typo fix] add missing apostrophe

---

docs/index.md

In order to make the tutorial flow more seamlessly, and not require users to troubleshoot the localhost redirects and env format etc I added a quick note to the documentation about to run this tutorial if the docker environment is in a Linux VM etc and the ports are not exposed on localhost.

Documented how to set external URL [#163]

---

docs/basics/parameters.md
docs/basics/pipeline-jobs.md
docs/basics/pipeline-resources.md
docs/basics/publishing-outputs.md
docs/basics/task-hello-world.md
docs/basics/task-outputs-to-inputs.md
docs/basics/task-scripts.md
docs/basics/trigger-jobs.md
docs/index.md
docs/miscellaneous/index.md
docs/miscellaneous/run-tests-before-deploy.md
docs/miscellaneous/slack-notifications.md
docs/miscellaneous/yaml-editors.md
mkdocs.yml

Fixing links to follow MKDOCS standards.   
+ pages should use relative markdown style to where the page is located (../basics/introduction.md) from the miscellaneous directory 
+ images use relative to the top of site standard   (/images/display.pin)

fixed links to mkdocs standards

---

README.md
docs/basics/basic-pipeline.md
docs/basics/job-inputs.md
docs/basics/parameters.md
docs/basics/pipeline-jobs.md
docs/basics/pipeline-resources.md
docs/basics/publishing-outputs.md
docs/basics/secret-parameters.md
docs/basics/task-inputs.md
docs/basics/task-outputs-to-inputs.md
docs/basics/task-scripts.md
docs/basics/triggers.md
docs/index.md
docs/miscellaneous/docker-images.md
docs/miscellaneous/github-release-input.md
docs/miscellaneous/run-tests-before-deploy.md
docs/miscellaneous/slack-notifications.md
docs/miscellaneous/versions-and-buildnumbers.md

As per issue #144 I have updated to use the long operational names.   I also added a section fly help and discussed the short operational names there.    Added changes about docker compose from docker-compose.

Use fly long commands

---

docs/basics/task-scripts.md

For Windows users, some may see this error `uname: invalid option --` when you execute the fly command. This may have happened because when the repo was downloaded on Windows machine,  Windows style line ending have been applied to the `task_show_uname.sh` file. One way to fix that is to open up the file in Notepad++, click on "Edit->EOL Conversion->Unix". Save the file and execute the fly command again.

Updated docs to fix an error on Windows
